- hosts: '{{ hosts }}'
  sudo: yes
  vars_files: 
     - ../../common-vars/common.yml
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     - ../../system-vars/{{ system }}-{{ env }}.yml

  roles:
     - ../../common-roles/fusionio/10_snmp-agent
