- name: add dmmadmin group
  action: group name=dmmadmin gid=1001 state=present
  tags:
     - account

- name: add dmmadmin user
  action: user name=dmmadmin uid=1001 group=dmmadmin groups=wheel append=yes state=present force=yes
  ignore_errors: yes
  tags:
     - account
