- name: update /etc/yum.conf
  action: raw sed '/proxy.*/d' /etc/yum.conf -i
  tags:
    - yum

- name: update /etc/yum.conf
  action: raw echo proxy={{ http_proxy }} >> /etc/yum.conf
  tags:
    - yum

- name: set old releasever if [ releasever ] is defined
  action: raw {{ item }}
  with_items:
    - echo "{{ releasever }}" > /etc/yum/vars/releasever
    - sed -e 's@#baseurl=http://mirror.centos.org/centos@baseurl=http://vault.centos.org@g' /etc/yum.repos.d/CentOS-Base.repo -i.org
  when: releasever is defined
  tags:
    - yum

- name: remove /etc/yum/vars/releasever if [ releasever ] is not defined
  action: raw {{ item }}
  with_items:
    - rm -f /etc/yum/vars/releasever
  when: releasever is not defined
  tags:
    - yum

- name: install required for ansible
  action: yum name={{ item }} state=present
  with_items:
    - libselinux-python
  tags:
    - yum

- name: update /etc/yum.conf
  action: lineinfile dest=/etc/yum.conf  regexp='^keepcache' line='keepcache=1'
  tags:
    - yum

- name: update /etc/yum.conf
  action: lineinfile dest=/etc/yum.conf regexp='.*proxy=.*' line='proxy={{ http_proxy }}'
  tags:
    - yum

- name: update all package
  action: yum name=* state=latest disable_gpg_check=yes
  tags:
    - yum

- name: update /etc/yum.conf
  action: lineinfile dest=/etc/yum.conf  regexp='.*exclude=kernel' line='# exclude=kernel* centos-release*'
  tags:
    - yum

- name: install packages in @base group
  action: yum name={{ item }} state=latest
  with_items:
    - eject
    - iptables
    - man
    - man-pages
    - mlocate
    - nfs-utils
    - nss_ldap
    - openssh-clients
    - openssh-server
    - rsync
    - sendmail
    - sudo
    - tcp_wrappers
    - tcpdump
    - telnet
    - time
    - vconfig
    - wget
    - which
    - yum
  tags:
    - packages

- name: install all packages in @core group
  action: yum name=@core state=latest
  tags:
    - packages

- name: install all packages in @development-libs group
  action: yum name=@development-libs state=latest
  tags:
    - packages

- name: install all packages in @development group
  action: yum name=@development state=latest
  tags:
    - packages

- name: install make packages
  action: yum name={{ item }} state=latest
  with_items:
    - make
  tags:
    - packages

- name: install all packages in @system-tools group
  action: yum name={{ item }} state=latest
  with_items:
    - net-snmp-libs
    - net-snmp-utils
    - ntp
    - screen
    - sysstat
  tags:
    - packages  

- name: install packages in @legacy-network-server
  action: yum name={{ item }} state=latest
  with_items:
    - xinetd
  tags:
    - package

- name: remove all packages in @dialup
  action: yum name=@dialup state=removed
  tags:
    - package

- name: remove all packages in @editor
  action: yum name=@editor state=removed
  tags:
    - package

- name: update /etc/yum.conf
  action: lineinfile dest=/etc/yum.conf regexp='.*exclude=kernel' line='exclude=kernel* centos-release*'
  tags:
    - yum
