- name: check kafka installed
  stat: path=/usr/local/kafka_{{ scala_major_version }}-{{ kafka_version }}
  register: kafka
  failed_when: not kafka.stat.exists
  tags:
    - kafka

- name: copy kafka init script
  template: src=kafka.init.j2 dest=/etc/init.d/kafka group=root owner=root mode=755 backup=no
  tags:
    - kafka

- name: copy kafka config file
  template: src=server.properties.j2 dest=/usr/local/kafka_{{ scala_major_version }}-{{ kafka_version }}/config/server.properties group=root owner=root mode=644 backup=yes
  tags:
    - kafka

- name: add group kafka
  group: name={{ kafka_group }} state=present
  tags:
    - kafka

- name: add user kafka
  user: name={{ kafka_user }} comment="{{ kafka_user }}" group={{ kafka_group }} state=present
  tags:
    - kafka

- name: create data directory
  file: path=/var/kafka owner={{ kafka_user }} group={{ kafka_group }} mode=755 state=directory recurse=yes
  tags:
    - kafka

- name: create log directory
  file: path=/var/log/kafka owner={{ kafka_user }} group={{ kafka_group }} mode=755 state=directory recurse=yes
  tags:
    - kafka

- name: Logrotate Configuration
  template: src=kafka.logrotate.j2 dest=/etc/logrotate.d/kafka mode=644 owner=root group=root

- name: enable kafka service
  service: name=kafka enabled=yes
  tags:
    - kafka

