- name: create directory
  file: dest={{ item }} state=directory mode=0777 owner=zabbix group=zabbix
  with_items:
    - /opt/capcom/
    - /opt/capcom/zabbix/
    - /opt/capcom/zabbix/dat/
  tags:
    - zabbix

- name: copy cron.d file
  copy: src=zabbix-lifekeeper dest=/etc/cron.d/ 
  tags:
    - zabbix
    - lifekeeper

- name: copy userparameter file
  copy: src=userparameter_lifekeeper.conf dest=/etc/zabbix/zabbix_agentd.d/userparameter_lifekeeper.conf
  register: userparameter
  tags:
    - zabbix
    - lifekeeper

- name: restart zabbix-agent
  service: name=zabbix-agent state=restarted
  when: userparameter.changed
  tags:
    - zabbix

