- hosts: '{{ hosts }}'
  sudo: no
  vars_files: 
     - ../../common-vars/common.yml
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     - ../../system-vars/{{ system }}-{{ env }}.yml

  roles:
     - ../../common-roles/zabbix-agent/01_zabbix-agent
