- hosts: '{{ hosts }}'
  sudo: yes
  vars_files:
     # common vars file
     - ../../common-vars/common.yml
     # platform vars file
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-{{ env }}.yml

  vars:
     # must parameters
       # 0:disable 1:enable, recommend:0
       mysql_autocommit: 1
 
       # choise one from { READ-UNCOMMITTED | READ-COMMITTED | REPEATABLE-READ | SERIALIZABLE }, recommond:REPEATABLE-READ
       mysql_transaction_isolation: REPEATABLE-READ

       # performance option
       mysql_max_connections: 80
       mysql_wait_timeout: 28800
       mysql_interactive_timeout: 28800

     # not must parameters

       ### Global ###
       # default none
       # mysql_instance_name: 
       #
       # default 3306
       # mysql_port:
       #
       # enable:1 disable:0, default:1
       # mysql_use_performance_schema: 1
       #
       # default 60
       # mysql_log_throttle_queries_not_using_indexes: 60
       #
       # default 7(days)
       mysql_expire_log_days: 20

       ### InnoDB ###
       # default about 70% of total memory
       # mysql_innodb_buffer_pool_size: 
       #
       # default 64M
       # mysql_innodb_log_buffer_size: 64M
       #
       # default 256M
       # mysql_innodb_log_file_size: 256M
       #
       # default 10000(set 100000 over when using ssd)
       # mysql_innodb_io_capacity: 10000
       #

       ### MyISAM ###
       # default 64M
       # mysql_key_buffer_size: 64M
       #
       # default 8M
       # mysql_myisam_sort_buffer_size: 8M
       #
       # default 4096
       # percona_innodb_log_block_size: 4096
       #
       # default 60 
       # percona_thread_pool_idle_timeout: 60
       #
       # default 100000
       # percona_thread_pool_max_threads: 100000

     # replication parameter(not must)
       # default none
       mysql_replication_do_db:
          - zabbix

  roles:
    - ../../common-roles/php55/01_install_php55
    - ../../common-roles/php55/10_install_php-opcache
    - ../../common-roles/nginx-server/01_install_nginx-server
    - ../../common-roles/php55/10_install_php-fpm55
    - ../../common-roles/percona/01_install_percona-server
    - ../../common-roles/percona/02_setup_percona-server
    - ../../common-roles/zabbix-server/01_install_zabbix-server3
    - ../../common-roles/zabbix-server/11_setup_zabbix3-db
    - ../../common-roles/zabbix-server/12_add-conf_nginx-php-fpm
    - ../../common-roles/zabbix-server/13_setup_zabbix-server
