- hosts: '{{ hosts }}'
  sudo: yes
  vars_files:
     # common vars file
     - ../../common-vars/common.yml
     # platform vars file
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-{{ env }}.yml

  roles:
    - ../../platform-roles/capcomcloud/01_network-scripts
    - ../../platform-roles/capcomcloud/02_static-routes_to_management
    - ../../platform-roles/capcomcloud/02_static-routes_to_vpnclient
    - ../../platform-roles/capcomcloud/10_network-offload

