- name: add /usr/local/lib to shared library
  action: lineinfile dest=/etc/ld.so.conf {{item}} backup=yes
  with_items:
    - line='/usr/local/lib'
  register: add_library 
  tags:
    - shared_library

- name: reload library cache
  shell: /sbin/ldconfig
  when: add_library.changed
  tags:
    - shared_library
