- name: add dell-omsa repository
  copy: src=dell-omsa-repository.repo dest=/etc/yum.repos.d/
  when: ansible_system_vendor == "Dell Inc."
  tags:
    - install

- name: install required packages
  yum: pkg={{ item }} enablerepo=dell-omsa-specific,dell-omsa-indep state=latest
  with_items:
    - libsmbios
    - python-smbios
    - smbios-utils-python
    - yum-dellsysid
  when: ansible_system_vendor == "Dell Inc."
  tags:
    - install

- name: install omsa-packages
  yum: pkg=srvadmin-all enablerepo=dell-omsa-specific,dell-omsa-indep state=latest
  when: ansible_system_vendor == "Dell Inc."
  tags:
    - install

- name: update snmpd.conf
  lineinfile: dest=/etc/snmp/snmpd.conf line='smuxpeer .1.3.6.1.4.1.674.10892.1' state=present 
  when: ansible_system_vendor == "Dell Inc."
  tags:
    - setup

- name: startup omsa services
  service: name={{ item }} state=restarted enabled=yes
  with_items:
     - instsvcdrv
     - dsm_om_connsvc
     - dsm_om_shrsvc
     - dataeng
     - snmpd
  when: ansible_system_vendor == "Dell Inc."
  tags:
     - setup
