- name: install required packages
  action: yum name={{ item }} state=latest
  with_items:
    - libevent-devel 
  tags:
    - memcached

- name: copy memcached source file
  action: copy src=memcached-{{ memcached_version }}.tar.gz dest=/usr/local/src/
  tags:
    - memcached

- name: create memcached group
  action: group name=memcached gid=5002 state=present
  tags:
    - memcached

- name: create memcached user
  action: user name=memcached uid=5002 group=memcached home=/var/run/memcached shell=/sbin/nologin state=present 
  tags:
    - memcached

- name: create log directory
  action: file path=/var/log/memcached state=directory owner=memcached group=memcached
  tags:
    - memcached

- name: extract memcached source file
  action: shell tar xvzf memcached-{{ memcached_version }}.tar.gz chdir=/usr/local/src/
  tags:
    - memcached

- name: configure memcached
  action: shell ./configure --prefix=/usr/local/memcached-{{ memcached_version }} chdir=/usr/local/src/{{ memcached_version }}
  tags:
    - memcached

- name: make && make install repcached
  action: shell make && porg -lD "make install" chdir=/usr/local/src/memcached-{{ memcached_version }}
  tags:
    - memcached

- name: create symlink
  action: file state=link src=/usr/local/memcached-{{ memcached_version }} dest=/usr/local/memcached
  tags:
    - memcached

- name: copy sysconfig file
  action: template src=etc_sysconfig_memcached dest=/etc/sysconfig/memcached
  tags:
    - memcached

- name: copy init script
  action: template src=etc_init.d_memcached dest=/etc/init.d/memcached mode=0755
  tags:
    - memcached

- name: add memcached service
  action: shell chkconfig --add memcached 
  tags:
    - memcached

- name: start memcached service
  action: service name=memcached state=restarted enabled=yes
  tags:
    - memcached
