- name: install patch package
  action: yum name=patch state=latest
  tags:
    - gnu_bash

- name: copy gnu bash src file
  action: copy src=bash-{{ gnu_bash_version }}.tar.gz dest=/usr/local/src/
  tags:
    - gnu_bash

- name: remove old bash src file
  shell: file path=/usr/local/src/bash-{{ gnu_bash_version }} state=absent recurse=true
  tags:
    - gnu_bash

- name: extract gnu bash src file
  shell: tar xvzf /usr/local/src/bash-{{ gnu_bash_version }}.tar.gz -C /usr/local/src/
  tags:
    - gnu_bash

- name: put patch files
  action: copy src={{ item }} dest=/usr/local/src/bash-{{ gnu_bash_version }}/patches/
  with_items:
    - bash43-001
    - bash43-002
    - bash43-003
    - bash43-004
    - bash43-005
    - bash43-006
    - bash43-007
    - bash43-008
    - bash43-009
    - bash43-010
    - bash43-011
    - bash43-012
    - bash43-013
    - bash43-014
    - bash43-015
    - bash43-016
    - bash43-017
    - bash43-018
    - bash43-019
    - bash43-020
    - bash43-021
    - bash43-022
    - bash43-023
    - bash43-024
    - bash43-025
    - bash43-026
    - bash43-027
    - bash43-028
    - bash43-029
    - bash43-030
    - bash43-031
    - bash43-032
    - bash43-033
  tags:
    - gnu_bash

- name: apply patches gnu bash
  action: shell patch -p0 < patches/{{ item }}  chdir=/usr/local/src/bash-{{ gnu_bash_version }}/
  with_items:
    - bash43-001
    - bash43-002
    - bash43-003
    - bash43-004
    - bash43-005
    - bash43-006
    - bash43-007
    - bash43-008
    - bash43-009
    - bash43-010
    - bash43-011
    - bash43-012
    - bash43-013
    - bash43-014
    - bash43-015
    - bash43-016
    - bash43-017
    - bash43-018
    - bash43-019
    - bash43-020
    - bash43-021
    - bash43-022
    - bash43-023
    - bash43-024
    - bash43-025
    - bash43-026
    - bash43-027
    - bash43-028
    - bash43-029
    - bash43-030
    - bash43-031
    - bash43-032
    - bash43-033
  tags:
    - gnu_bash

- name: enable bash history
  lineinfile: dest=/usr/local/src/bash-{{ gnu_bash_version }}/config-top.h regexp='#define SYSLOG_HISTORY' line='#define SYSLOG_HISTORY' state=present insertbefore='#if defined (SYSLOG_HISTORY)'
  tags:
    - gnu_bash

- name: change bash history log format
  lineinfile: dest=/usr/local/src/bash-{{ gnu_bash_version }}/bashhist.c regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
    - { regexp: 'HISTORY:', line: '    syslog (SYSLOG_FACILITY|SYSLOG_LEVEL, \"HISTORY: PID=%d PPID=%d SID=%d USER=%s CMD=%s\" , getpid(), getppid (), getsid(getpid()), current_user.user_name, line);' }
    - { regexp: 'HISTORY \(TRUNCATED\):', line: '      syslog (SYSLOG_FACILITY|SYSLOG_LEVEL, \"HISTORY (TRUNCATED): PID=%d PPID=%d SID=%d USER=%s CMD=%s\" , getpid(), getppid (), getsid(getpid()), current_user.user_name, trunc);' }
  tags:
    - gnu_bash

- name: compile & install gnu bash
  shell: cd /usr/local/src/bash-{{ gnu_bash_version }}/ && ./configure && make && porg -lD "make install"
  tags:
    - gnu_bash

- name: change login shell to /usr/local/bin/bash
  user: name={{ item }} shell=/usr/local/bin/bash
  with_items:
    - capadmin
    - root
  tags:
    - gnu_bash

