- name: configure /root/.bash_profile
  lineinfile: dest=/root/.bash_profile owner=root group=root mode=0644 backup=yes regexp="^PS1=" line="PS1=\"[\H]\\$ \""
  tags: bash_profile

- name: configure /root/.bash_profile
  lineinfile: dest=/root/.bash_profile owner=root group=root mode=0644 backup=yes regexp="^export PAGER=" line="export PAGER=\"less -IX\""
  tags: bash_profile

- name: configure /root/.bash_profile
  lineinfile: dest=/root/.bash_profile owner=root group=root mode=0644 backup=yes regexp="^export EDITOR=" line="export EDITOR=\"vi\""
  tags: bash_profile

- name: configure /root/.bash_profile
  lineinfile: dest=/root/.bash_profile owner=root group=root mode=0644 backup=yes regexp="^alias now=" line="alias now=\"date +%Y%m%d-%H%M%S\""
  tags: bash_profile
