#!/bin/sh
export JAVA_HOME=/usr/java/default/
export JRE_HOME=/usr/java/default/jre/
export CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH
export TOMCAT_HOME=/usr/local/tomcat
export LD_LIBRARY_PATH=$TOMCAT_HOME/lib
export CATALINA_HOME=/usr/local/tomcat
export CLASSPATH=$CLASSPATH:$CATALINA_HOME/common/lib
export CATALINA_PID=/var/run/tomcat.pid
export CATALINA_OPTS=" \
-server \
-XX:+DisableExplicitGC \
-Xms{{ tomcat_xms | default("1536m") }} \
-Xmx{{ tomcat_xmx | default("1536m") }} \
-XX:MaxPermSize={{ tomcat_maxpermsize | default("512m") }} \
-XX:NewSize={{ tomcat_newsize | default("512m") }} \
-XX:MaxNewSize={{ tomcat_maxnewsize | default("512m") }} \
-XX:+UseParNewGC \
-XX:+UseConcMarkSweepGC \
-XX:+CMSParallelRemarkEnabled \
-XX:+UseTLAB \
-XX:MaxTenuringThreshold=32 \
-XX:TargetSurvivorRatio=90 \
-XX:SurvivorRatio=4 \
-XX:+ForceTimeHighResolution \
-Djava.awt.headless=true \
-Dcom.sun.management.jmxremote=true \
-Dcom.sun.management.jmxremote.port=10080 \
-Djava.net.preferIPv4Stack=true \
-Dcom.sun.management.jmxremote.ssl=falsae \
-Dcom.sun.management.jmxremote.authenticate=false" 
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:$CATALINA_HOME/lib/jolokia-jvm-agent.jar"
