- name: install munin,munin-node
  yum: name={{ item }} enablerepo=epel state=latest disable_gpg_check=yes
  with_items: 
    - 'munin'
    - 'munin-node'
  tags:
    - munin

- name: configure munin.conf
  template: src=munin.conf dest=/etc/munin/munin.conf backup=yes
  tags:
    - munin

- name: configure template http-equiv encode (to UTF-8)
  replace: dest=/etc/munin/templates/partial/head.tmpl replace='charset=UTF-8' regexp='charset=iso-8859-1'

- name: start munin
  service name=munin state=restarted enabled=yes
  tags:
    - munin

