- name: install required packages from repository
  action: yum name={{ item }} state=latest
  with_items:
    - pcre-devel
  tags:
    - nginx

- name: download zlib source file
  action: shell http_proxy={{ http_proxy }} wget -nc http://zlib.net/zlib-1.2.8.tar.gz chdir=/usr/local/src/
  tags:
    - nginx

- name: extract zlib source file
  action: shell tar xvzf {{ item }} chdir=/usr/local/src/
  with_items:
    - zlib-1.2.8.tar.gz
  tags:
    - nginx

- name: download nginx source file
  action: shell http_proxy={{ http_proxy }} wget -nc http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz  chdir=/usr/local/src/
  tags:
    - nginx

- name: extract source file
  action: shell tar xvzf {{ item }} chdir=/usr/local/src/
  with_items:
    - nginx-{{ nginx_version }}.tar.gz
  tags:
    - nginx

- name: copy nginx configure file
  action: template src=nginx-configure.sh dest=/usr/local/src/nginx-{{ nginx_version }}/
  tags:
    - nginx

- name: exec nginx configure file
  action: shell sh nginx-configure.sh chdir=/usr/local/src/nginx-{{ nginx_version }}/
  tags:
    - nginx

- name: make install nginx
  action: shell make && make install chdir=/usr/local/src/nginx-{{ nginx_version }}/
  tags:
    - nginx

- name: create symlink for nginx home directory
  action: file state=link src=/usr/local/nginx-{{nginx_version}} dest=/usr/local/nginx
  tags:
     - nginx

- name: create nginx log directories
  action: file state=directory path={{ item }}
  with_items:
    - /var/log/nginx/
  tags:
    - nginx

- name: create symlink for nginx log directory (1/2)
  action: file state=absent path=/usr/local/nginx/logs/
  tags:
    - nginx

- name: create symlink for nginx log directory (2/2)
  action: file state=link src=/var/log/nginx dest=/usr/local/nginx/logs
  tags:
    - nginx

- name: create nginx group
  action: group name=nginx gid=88
  tags:
    - nginx

- name: create nginx user
  action: user name=nginx uid=88 group=nginx createhome=yes home=/var/www/ shell=/sbin/nologin
  tags:
    - nginx

- name: copy nginx init script
  action: template src=etc_init.d_nginx dest=/etc/init.d/nginx mode=0755
  tags:
    - nginx

- name: create nginx pid directory
  action: file state=directory mode=0755 owner=root group=nginx path=/var/run/nginx/
  tags:
    - nginx

- name: add nginx service
  action: shell chkconfig --add nginx
  tags:
    - nginx

- name: start nginx service
  action: service name=nginx state=started enabled=yes
  tags:
    - nginx

