- name: create directory
  file: path={{ item }} state=directory mode=0755 owner=zabbix group=zabbix
  with_items:
    - /opt/capcom/
    - /opt/capcom/zabbix/
    - /opt/capcom/zabbix/bin/
    - /opt/capcom/zabbix/dat/

- name: put userparameter
  copy: src=userparameter_huawei_ssd.conf dest=/etc/zabbix/zabbix_agentd.d/ owner=root group=root mode=0644
  tags:
    - zabbix

- name: put script
  copy: src={{ item }} dest=/opt/capcom/zabbix/bin/ owner=zabbix group=zabbix mode=0755
  tags:
    - zabbix
  with_items:
    - huawei.ssd.discover.sh
    - huawei.ssd.hioinfo.sh

- name: setup cron for huawei ssd stat
  cron: name="huawei ssd stat" job="/opt/capcom/zabbix/bin/huawei.ssd.hioinfo.sh" minute="*/5" state=present
  tags:
    - zabbix

- name: restart zabbix-agent
  action: service name=zabbix-agent state=restarted
  tags:
    - zabbix
