- name: install dependancy 
  yum: name={{ item }} state=present
  with_items:
    - net-snmp
    - net-snmp-utils
    - lm_sensors-libs
    - lm_sensors
  tags:
    - setup

- name: copy rpm file
  copy: src={{ item }} dest=/tmp/
  with_items:
    - sas_snmp-15.11-0012.x86_64.rpm
    - sas_ir_snmp-15.11-0012.x86_64.rpm
  tags:
    - setup
  changed_when: False
  always_run: yes

- name: install rpm file
  yum: name={{ item }} state=present
  with_items:
    - /tmp/sas_snmp-15.11-0012.x86_64.rpm
    - /tmp/sas_ir_snmp-15.11-0012.x86_64.rpm
  tags:
    - setup

- name: delete rpm file
  file: path={{ item }} state=absent
  with_items:
    - /tmp/sas_snmp-15.11-0012.x86_64.rpm
    - /tmp/sas_ir_snmp-15.11-0012.x86_64.rpm
  tags:
    - setup
  changed_when: False
  always_run: yes

- name: update snmpd.conf
  lineinfile: dest=/etc/snmp/snmpd.conf line='pass .1.3.6.1.4.1.3582 /usr/sbin/lsi_mrdsnmpmain' state=present 
  tags:
     - setup

- name: enable and restart lsi_mrdsnmpd service
  service: name=lsi_mrdsnmpd state=restarted enabled=yes
  tags:
    - setup

- name: enable and restart snmp service
  service: name=snmpd state=restarted enabled=yes
  tags:
    - setup

