- name: install required packages
  yum: name={{ item }} state=latest
  with_items:
     - pciutils
     - lsof
     - tcl
     - hping3
  when: ansible_system_vendor == "HP"
  tags:
    - install

- name: add hp-mcp repository
  copy: src=hp-mcp.repo dest=/etc/yum.repos.d/
  when: ansible_system_vendor == "HP"
  tags:
    - install

- name: install mcp package
  yum: enablerepo=mcp disablerepo=base name={{ item }} disable_gpg_check=yes
  with_items:
    - cpqarrayd
    - hp-ams
    - hp-health
    - hp-smh-templates
    - hp-snmp-agents
    - hpdiags
    - hponcfg
    - hpsmh
    - hpssacli
  when: ansible_system_vendor == "HP"
  tags:
    - install

- name: start hp-snmp-agents
  service: name=hp-snmp-agents state=restarted
  when: ansible_system_vendor == "HP"
  tags:
    - setup

- name: update snmpd.conf into First Line
  lineinfile: dest=/etc/snmp/snmpd.conf line='dlmod cmaX /usr/lib64/libcmaX64.so' state=present insertbefore=BOF
  when: ansible_system_vendor == "HP"
  tags:
    - setup

- name: update snmpd.conf into EOF
  lineinfile: dest=/etc/snmp/snmpd.conf line="{{ item }}" state=present
  with_items:
    - 'pass .1.3.6.1.4.1.4413.4.1 /usr/bin/ucd5820stat'
    - 'pass .1.3.6.1.2.1.10.7.11.1 /usr/bin/nx_snmp.pl'
  when: ansible_system_vendor == "HP"
  tags:
    - setup

- name: restart snmpd
  service: name=snmpd state=restarted
  when: ansible_system_vendor == "HP"
  tags:
    - setup

