- name: install libselinux-python
  action: yum name=libselinux-python state=latest
  tags:
    - selinux

- name: Disable selinux
  action: selinux state=disabled
  tags:
    - selinux

- name: Get current policy
  action: shell getenforce
  register: getenforce_result
  tags:
    - selinux

- name: Disable current selinux if current policy is Enforcing.
  action: shell setenforce 0
  when: getenforce_result.stdout == "Enforcing"
  tags:
    - selinux
