- name: copy repository file
  action: copy src=treasuredata.repo dest=/etc/yum.repos.d/
  tags:
    - td-agent

- name: install td-agent
  action: yum name={{ item }} state=latest enablerepo=treasuredata
  with_items:
    - td-agent
    - libcurl-devel
  tags:
    - td-agent

- name: create conf directory
  action: file dest=/etc/td-agent/td-agent.conf.d/ state=directory
  tags:
    - td-agent

- name: create pos directory
  action: file dest=/var/log/td-agent/pos/ state=directory owner=td-agent group=td-agent
  tags:
    - td-agent

- name: create err directory
  action: file dest=/var/log/td-agent/err/ state=directory owner=td-agent group=td-agent mode=0777
  tags:
    - td-agent

- name: create buffer directory
  action: file dest=/tmp/td-agent/buffer/ state=directory owner=td-agent group=td-agent mode=0777
  tags:
    - td-agent

- name: copy base td-agent conf file
  action: copy src=td-agent.conf dest=/etc/td-agent/td-agent.conf backup=yes
  tags:
    - td-agent

- name: install plugins
  action: shell http_proxy={{ http_proxy }} td-agent-gem install {{ item }}
  with_items:
#    - fluent-plugin-tail-ex  # Deprecated: Fluentd has the features of this plugin since 0.10.45.
    - fluent-plugin-file-alternative
    - fluent-plugin-parser
    - fluent-plugin-filter
    - fluent-plugin-forest 
    - fluent-plugin-mongo
    - fluent-plugin-elasticsearch
    - fluent-plugin-multi-format-parser
    - fluent-plugin-remote_syslog
  tags:
    - td-agent

- name: copy monitor.conf to /etc/td-agent/td-agent.conf.d/
  action: copy src=monitor.conf dest=/etc/td-agent/td-agent.conf.d/
  tags:
    - td-agent

- name: start td-agent service
  action: service name=td-agent state=restarted
  tags:
    - td-agent

#- name: restart td-agent
#  action: raw service td-agent restart
#  tags:
#    - td-agent
