- name: remove cronie-anacron
  action: yum pkg={{ item }} state=removed
  with_items:
    - cronie-anacron
  tags:
    - anacron

- name: install cronie-noanacron
  action: yum pkg={{ item }} state=latest
  with_items:
    - cronie-noanacron
  tags:
    - anacron

- name: restart crond
  action: service name=crond state=restarted enabled=yes
  tags:
    - anacron
