- name: create zabbix database
  action: mysql_db name=zabbix encoding=utf8 state=present
  tags:
    - zabbix

- name: create zabbix user
  action: mysql_user name=zabbix password=zabbix append_privs=yes priv=zabbix.*:ALL state=present
  tags:
    - zabbix

- name: import initial schema to zabbix database
  action: shell mysql -uzabbix -pzabbix zabbix < /usr/share/doc/zabbix-server-mysql-$(zabbix_server -V | head -1 | awk '{print $3}' | sed -e 's/v//g')/create/schema.sql
  tags:
    - zabbix

- name: import initial images to zabbix database
  action: shell mysql -uzabbix -pzabbix zabbix < /usr/share/doc/zabbix-server-mysql-$(zabbix_server -V | head -1 | awk '{print $3}' | sed -e 's/v//g')/create/images.sql
  tags:
    - zabbix

- name: import initial data to zabbix database
  action: shell mysql -uzabbix -pzabbix zabbix < /usr/share/doc/zabbix-server-mysql-$(zabbix_server -V | head -1 | awk '{print $3}' | sed -e 's/v//g')/create/data.sql
  tags:
    - zabbix

- name: create sql dir
  action: file path=/opt/capcom/zabbix/sql/ state=directory owner=zabbix group=zabbix
  tags:
    - zabbix

- name: copy table complress sql
  action: copy src=zabbix_table_compress.sql dest=/opt/capcom/zabbix/sql/
  tags:
    - zabbix

- name: execute table compress sql
  action: shell mysql -uzabbix -pzabbix zabbix < /opt/capcom/zabbix/sql/zabbix_table_compress.sql
  tags:
    - zabbix
