- name: backup old file
  action: shell cp -pR /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.$(date +%Y%m%d-%H%M%S)
  tags:
    - apache

- name: put
  action: copy src=access_log_ltsv.conf dest=/etc/httpd/conf.d/
  tags:
    - apache

- name: change log format to ltsv
  action:  lineinfile dest=/etc/httpd/conf/httpd.conf backup=no regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
    - { regexp: '^CustomLog', line: 'CustomLog logs/access_log access_log_ltsv' }
  tags:
    - apache

- name: reload httpd server
  action: service name=httpd state=reloaded enabled=yes
  tags:
    - apache
