- hosts: '{{ hosts }}'
  sudo: no
  vars_files: 
     - ../../common-vars/common.yml

  roles:
     - ../../common-roles/apache/01_apache-server_with-src
#     - ../../common-roles/apache/01_apache-server
