- name: update /etc/ntp.conf
  template: src=ntp.conf dest=/etc/ntp.conf backup=yes
  tags: ntp

- name: update /etc/ntp/step-tickers
  template: src=step-tickers dest=/etc/ntp/step-tickers backup=yes
  tags: ntp

- name: update /etc/sysconfig/ntpdate(virtual machine)
  lineinfile: dest=/etc/sysconfig/ntpdate regexp='SYNC_HWCLOCK=' line='SYNC_HWCLOCK=no'
  when: ansible_virtualization_role is defined
  tags: ntp

- name: update /etc/sysconfig/ntpdate(physical machine)
  lineinfile: dest=/etc/sysconfig/ntpdate regexp='SYNC_HWCLOCK=' line='SYNC_HWCLOCK=yes'
  when: ansible_virtualization_role is not defined or ansible_virtualization_role=="NA"
  tags: ntp

- name: stop ntp service
  service: name=ntpd state=stopped
  tags: ntp

- name: exec ntpdate
  service: name=ntpdate state=restarted
  tags: ntp

- name: start ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: add cron job (restart ntpd & exec ntpdate)
  lineinfile: dest=/etc/cron.d/root-capcom-common state=present create=yes regexp='^# restart ntpd & exec ntpdate' line='# restart ntpd & exec ntpdate'
  tags: ntp

- name: add cron job (restart ntpd & exec ntpdate)
  lineinfile: dest=/etc/cron.d/root-capcom-common state=present create=yes regexp='service ntpdate restart' line='0 6 * * * root /bin/sleep $(/usr/bin/expr $RANDOM \% 180) ; /sbin/service ntpd stop ; /sbin/service ntpdate restart ; /sbin/service ntpd start' insertafter='# restart ntpd & exec ntpdate'
  tags: ntp

