- name: install required packages
  action: yum name={{ item }} state=latest
  with_items:
    - postfix
    - procmail
  tags:
    - mail
    - cog

- name: update main.cf
  action: template src={{ env }}-main.cf dest=/etc/postfix/main.cf
  tags:
    - cog
    - mail

- name: update /etc/aliases
  action: template src={{ env }}-etc_aliases dest=/etc/aliases
  tags:
    - cog
    - mail

- name: copy python script
  action: template src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
    - { src: usr_local_bin_procmail-info.py, dest: /usr/local/bin/procmail-info.py }
    - { src: usr_local_bin_procmail-mag.py, dest: /usr/local/bin/procmail-mag.py }
  tags:
    - cog
    - mail

- name: copy procmailrc-info
  action: template src={{ env }}-usr_local_etc_procmailrc-info dest=/usr/local/etc/procmailrc-info
  tags:
    - cog
    - mail

- name: copy procmailrc-mag
  action: template src={{ env }}-usr_local_etc_procmailrc-mag dest=/usr/local/etc/procmailrc-mag
  tags:
    - cog
    - mail

- name: create mail directory
  action: file path={{ item }} state=directory owner=root group=root mode=777
  with_items:
    - /var/log/daletto/
    - /var/log/daletto/mail/
  tags:
    - cog
    - mail

- name: restart postfix
  action: service name=postfix state=restarted
  tags:
    - cog
    - mail

- name: change permission of maillog
  action: file dest=/var/log/maillog mode=0644 state=present
  tags:
    - cog
    - mail
