- name: shell directory
  file: state=directory path={{ item.path }}  mode={{ item.mode }} owner={{ item.owner }}  group={{ item.group }}
  with_items:
     - { path: '/opt/capcom' ,  mode: '0777' , owner: 'root' , group: 'root' }
     - { path: '/opt/capcom/bin' ,  mode: '0777' , owner: 'root' , group: 'root' }
     - { path: '/opt/capcom/log' ,  mode: '0777' , owner: 'root' , group: 'root' }
     - { path: '/var/pgsql/pg_rman/log' ,  mode: '0777' , owner: 'postgres' , group: 'postgres' }

- name: copy source file
  copy: src={{ item }} dest=/opt/capcom/bin/ backup=yes mode=0744
  with_items:
    - pgrman_base.sh
    - pgrman_increment.sh

- name: edit crontab pg_rman full backup
  cron: name="[postgresql pr_rman] full backup" minute="0" hour="4,14" weekday="1,2,4-7" job="/opt/capcom/bin/pgrman_base.sh > /opt/capcom/log/pgrman_base.sh_`date +\%Y\%m\%d-\%H\%M`.log 2>&1" 
- name: edit crontab pg_rman full backup Wednesday
  cron: name="[postgresql pr_rman] full backup Wednesday" minute="0" hour="4,17" weekday="3" job="/opt/capcom/bin/pgrman_base.sh > /opt/capcom/log/pgrman_base.sh_`date +\%Y\%m\%d-\%H\%M`.log 2>&1" 

- name: edit crontab pg_rman incremental backup
  cron: name="[postgresql pr_rman] incremental backup" minute="2,32" hour="0-3,5-13,15-23" weekday="1,2,4-7" job="/opt/capcom/bin/pgrman_increment.sh > /opt/capcom/log/pgrman_increment.sh_`date +\%Y\%m\%d-\%H\%M`.log 2>&1"
- name: edit crontab pg_rman incremental backup Wednesday
  cron: name="[postgresql pr_rman] incremental backup Wednesday" minute="2,32" hour="0-3,5-16,18-23" weekday="3" job="/opt/capcom/bin/pgrman_increment.sh > /opt/capcom/log/pgrman_increment.sh_`date +\%Y\%m\%d-\%H\%M`.log 2>&1"

- name: edit crontab delete shell log pg_rman
  cron: name="[delete shell log] /var/pgsql/pg_rman/log" minute="0" hour="5" job="find /var/pgsql/pg_rman/log/ -mtime +8 -name *.log | xargs /bin/rm"
- name: edit crontab delete shell log capcom/log
  cron: name="[delete shell log] /opt/capcom/log" minute="0" hour="5" job="find /opt/capcom/log/ -mtime +8 -name *.log | xargs /bin/rm"
