- name : check exist sorce file
  command : ls {{src_dir}}/{{product_name}}-{{product_ver}}.tar.gz
  ignore_errors: True
  register: result1

- name: copy source file
  copy : src={{product_name}}-{{product_ver}}.tar.gz dest={{src_dir}}

- name : check exist sorce file
  command : ls {{src_dir}}/{{product_name}}-{{product_ver}}
  ignore_errors: True
  register: result2

- name: install packages in libxml2 for pg_statsinfo
  action: yum pkg={{ item }} state=latest

  with_items:
    - readline
    - readline-devel
    - libxml2
    - libxml2-devel
  tags:
    - packages

- name : tar
  command : tar xvfz {{product_name}}-{{product_ver}}.tar.gz chdir={{src_dir}} creates={{src_dir}}/{{product_name}}-{{product_ver}}
  when: result2|failed

- name: check install
  command: ls {{dst_dir}}/{{product_linkname}}-{{product_ver}}/bin/{{product_bin}}
  ignore_errors: True
  register: result3

- name : config
  command : ./configure --with-libxml --prefix={{dst_dir}}/{{product_linkname}}-{{product_ver}} chdir={{src_dir}}/{{product_name}}-{{product_ver}}
  when: result3|failed

- name : make
  command : make chdir={{src_dir}}/{{product_name}}-{{product_ver}}
  when: result3|failed

- name : make install
  command : make install chdir={{src_dir}}/{{product_name}}-{{product_ver}}
  when: result3|failed

#- name: link
#  action : file force=yes src='{{dst_dir}}/{{product_linkname}}-{{product_ver}}' dest='{{dst_dir}}/{{product_linkname}}' state=link
