- name: create directory
  file: dest={{ item }} state=directory mode=0777 owner=zabbix group=zabbix
  with_items:
    - /opt/capcom/
    - /opt/capcom/zabbix/
    - /opt/capcom/zabbix/dat/
  tags:
    - zabbix

- name: create directory
  file: dest={{ item }} state=directory mode=0700 owner=zabbix group=zabbix
  with_items:
    - /var/lib/zabbix/
  tags:
    - zabbix

- name: copy userparameter file
  copy: src=userparameter_oracle.conf dest=/etc/zabbix/zabbix_agentd.d/userparameter_oracle.conf
  register: userparameter
  tags:
    - zabbix
    - oracle

- name: restart zabbix-agent
  service: name=zabbix-agent state=restarted
  when: userparameter.changed
  tags:
    - zabbix
