- name: create working directory
  file: path=/usr/local/src/ansible-cmdb/ state=directory

- name: copy files
  synchronize: src=../files/ dest=/usr/local/src/ansible-cmdb/ recursive=yes

- name: search rpm file
  shell: ls -1 /usr/local/src/ansible-cmdb/*.rpm
  always_run: yes
  register: rpmfiles

#- set_fact: remain_packages={{ yum_packages|difference(rpmfiles.stdout)|join(' ') }}
 
#- debug: msg="{{ remain_packages }}"
#  when: remain_packages|length > 0


- name: install rpm package
  yum: name={{ rpmfiles.stdout }} state=present
  when: rpmfiles.stdout|length > 0

- name: create working directory
  file: path=/var/ansible-cmdb state=directory
