- name: precheck ldap client
  shell: getent passwd | grep -q sys
  register: ldap_client_setup
  failed_when: ldap_client_setup.rc not in [0, 1]
  tags: setup

- name: install ldap client package
  yum: name={{ item }} state=latest
  with_items:
    - nss_ldap
    - authconfig
    - openldap-clients
  tags: setup

- name: create cacerts directory
  action: file state=directory dest=/etc/openldap/cacerts/
  tags: setup

- name: copy ldap ssl cert
  action: copy src=server.crt.{{ platform }}-{{ env }} dest=/etc/openldap/cacerts/server.crt

- name: setup ldap client(platform ldapserver + system ldapserver)
  shell: authconfig --enableldap --enableldapauth --ldapserver={{ platform_ldapservers | union(system_ldapservers) | unique | join(",") }} --ldapbasedn="dc=capcom,dc=com" --update
  when: ldap_client_setup.rc == 1 and platform_ldapservers is defined and system_ldapservers is defined
  tags: setup

- name: setup ldap client(platform ldapserver only)
  shell: authconfig --enableldap --enableldapauth --ldapserver={{ platform_ldapservers | unique | join(",") }} --ldapbasedn="dc=capcom,dc=com" --update
  when: ldap_client_setup.rc == 1 and platform_ldapservers is defined and system_ldapservers is not defined
  tags: setup

- name: setup ldap client(system ldapserver only)
  shell: authconfig --enableldap --enableldapauth --ldapserver={{ system_ldapservers | unique | join(",") }} --ldapbasedn="dc=capcom,dc=com" --update
  when: ldap_client_setup.rc == 1 and platform_ldapservers is not defined and system_ldapservers is defined
  tags: setup

- name: update /etc/openldap/ldap.conf
  template: src=ldap.conf dest=/etc/openldap/ldap.conf backup=yes
  when: ldap_client_setup.rc == 1
  tags: setup

- name: update pam.d/system-auth-ac
  action: copy src=system-auth-ac dest=/etc/pam.d/system-auth-ac
  tags: setup

#- name: update pam.d/system-auth-ac
#  lineinfile: dest=/etc/pam.d/system-auth-ac
#              backup=yes
#              state="{{item.state}}"
#              regexp="{{item.regexp}}"
#              line="{{item.line}}"
#  with_items:
#    - { state: 'present' , regexp: '' , line: 'session     optional      pam_mkhomedir.so skel=/etc/skel umask=077' }
#    - { state: 'present' , regexp: 'account.*pam_ldap.so', line: 'account     [default=bad success=ok user_unknown=ignore service_err=ignore system_err=ignore authinfo_unavail=ignore] pam_ldap.so' }
#  tags:
#    - setup
#    - system-auth-ac
  

#- name: disable fingerprint
#  shell: authconfig --disablefingerprint --update
#  tags:
#    - fingerprint

- name: restart nscd service
  action: service name={{ item }} state=restarted
  with_items:
     - nscd
  tags: setup

- name: check ldap client
  shell: getent passwd | grep -q sys
  when: ldap_client_setup.rc == 1
  register: check_client
  tags: setup
