- hosts: '{{ hosts }}'
  sudo: yes
  vars_files:
     # common vars file
     - ../../common-vars/common.yml
     # platform vars file
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-{{ env }}.yml
     # subsystem vars file
     - ../../system-vars/{{ system }}-{{ subsystem }}-{{ env }}.yml

  roles:
     - ../../common-roles/apache/01_apache-server
     - ../../common-roles/php/01_install_php
     - ../../common-roles/php/10_install_php-apc
     - ../../system-roles/cog/portal-fronttools
