- hosts: '{{ hosts }}'
  sudo: yes
  vars_files:
     # common vars file
     - ../../common-vars/common.yml
     # platform vars file
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-{{ env }}.yml
     # subsystem vars file 
     - ../../system-vars/{{ system }}-{{ subsystem }}-{{ env }}.yml

  roles:
     - ../../common-roles/percona/01_install_percona-server
     - ../../common-roles/percona/02_setup_percona-server
     - ../../system-roles/cog/portal-db
