- hosts: '{{ hosts }}'
  sudo: yes
  vars_files:
     # common vars file
     - ../../common-vars/common.yml
     # platform vars file
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-{{ env }}.yml

  vars:
     mysql_master_replication-ip:
       - 10.105.2.101

     mysql_slave_replication-ip:
       - 10.105.2.102

     mysql_master-ha_backend-ip:
       - 10.104.2.109

     mysql_master-ha_replication-ip:
       - 10.105.2.109

  roles:
     - ../../common-roles/percona/11_exchange_ssh-key
     - ../../common-roles/percona/31_setup_master-ha-node
     - ../../common-roles/percona/32_setup_master-ha-manager
