- hosts: '{{ hosts }}'
  sudo: yes
  vars_files:
     # common vars file
     - ../../common-vars/common.yml
     # platform vars file
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-{{ env }}.yml

  vars:
       memcached_maxconn: 1000
       memcached_cachesize_mb: 1536

  roles:
     - ../../common-roles/repcached/01_install_repcached
     - ../../common-roles/monit/01_install_monit
     - ../../common-roles/ucarp/01_install_ucarp
     - ../../system-roles/cog/frontendapi-memcached
