- name: install required packages
  action: yum name={{ item }} state=latest
  with_items:
    - python-devel
    - zlib
    - zlib-devel
    - tk-devel
    - tcl-devel
    - sqlite-devel
    - ncurses-devel
    - gdbm-devel
    - readline-devel
    - bzip2-devel
    - db4-devel
    - openssl-devel
    - mod_wsgi
  tags:
    - python
