- name: precheck ldap client
  shell: getent passwd | grep -q sys
  register: ldap_client_setup
  failed_when: ldap_client_setup.rc not in [0, 1]
  tags: setup

- name: install ldap client package
  yum: name={{ item }} state=latest
  with_items:
    - openldap-clients
    - nss-pam-ldapd
    - authconfig
  tags: setup

- name: create cacerts directory
  action: file state=directory dest=/etc/openldap/cacerts/
  tags: setup

- name: copy ldap ssl cert
  action: copy src=server.crt.{{ platform }}-{{ env }} dest=/etc/openldap/cacerts/server.crt

- name: setup ldap client(platform ldapserver + system ldapserver)
  shell: authconfig --enableldap --enableldapauth --ldapserver={{ platform_ldapservers | union(system_ldapservers) | unique | join(",") }} --ldapbasedn="dc=capcom,dc=com" --update
  when: platform_ldapservers is defined and system_ldapservers is defined
  tags: setup

- name: setup ldap client(platform ldapserver only)
  shell: authconfig --enableldap --enableldapauth --ldapserver={{ platform_ldapservers | unique | join(",") }} --ldapbasedn="dc=capcom,dc=com" --update
  when: platform_ldapservers is defined and system_ldapservers is not defined
  tags: setup

- name: setup ldap client(system ldapserver only)
  shell: authconfig --enableldap --enableldapauth --ldapserver={{ system_ldapservers | unique | join(",") }} --ldapbasedn="dc=capcom,dc=com" --update
  when: platform_ldapservers is not defined and system_ldapservers is defined
  tags: setup

- name: update /etc/openldap/ldap.conf
  template: src=ldap.conf dest=/etc/openldap/ldap.conf backup=yes
  tags: setup

- name: update pam.d/system-auth-ac
  lineinfile: dest=/etc/pam.d/system-auth-ac backup=yes state=present line='session     optional      pam_mkhomedir.so skel=/etc/skel umask=077'
  tags:
    - setup
    - system-auth-ac
  
- name: update pam.d/system-auth-ac
  lineinfile: dest=/etc/pam.d/system-auth-ac backup=yes regexp='account.*pam_ldap.so' line='account     [default=bad success=ok user_unknown=ignore service_err=ignore system_err=ignore authinfo_unavail=ignore] pam_ldap.so'
  tags:
    - setup
    - system-auth-ac

- name: update pam.d/password-auth-ac
  lineinfile: dest=/etc/pam.d/password-auth-ac backup=yes state=present line='session     optional      pam_mkhomedir.so skel=/etc/skel umask=077'
  tags: 
     - setup
     - password-auth-ac

- name: update pam.d/password-auth-ac
  lineinfile: dest=/etc/pam.d/password-auth-ac backup=yes regexp='account.*pam_ldap.so' line='account     [default=bad success=ok user_unknown=ignore service_err=ignore system_err=ignore authinfo_unavail=ignore] pam_ldap.so'
  tags:
     - setup
     - password-auth-ac

- name: copy /etc/nslcd.conf
  template: src=nslcd.conf dest=/etc/nslcd.conf backup=yes
  tags: setup

- name: copy /etc/pam_ldap.conf
  template: src=pam_ldap.conf dest=/etc/pam_ldap.conf backup=yes
  tags: setup

- name: disable fingerprint
  shell: authconfig --disablefingerprint --update
  tags:
    - fingerprint

- name: restart nslcd and nscd service
  action: service name={{ item }} state=restarted
  with_items:
     - nslcd
     - nscd
  tags: setup

- name: check ldap client
  shell: getent passwd | grep -q sys
  register: check_client
  tags: setup
