- name: install snmp
  yum: name={{ item }} state=present
  with_items:
    - net-snmp
    - net-snmp-utils
    - lm_sensors-libs
    - lm_sensors
  tags:
    - install

- name: setup snmpd.conf
  template: src=snmpd.conf dest=/etc/snmp/snmpd.conf owner=root group=root mode=600 backup=yes
  tags:
    - install

- name: update /etc/init.d/snmpd
  lineinfile: dest=/etc/init.d/snmpd regexp="OPTIONS=.*" line='OPTIONS="-Lf /dev/null -p /var/run/snmpd.pid -a"' 
  tags:
    - setup
  when: ansible_distribution_major_version == "6"

- name: start snmp service
  service: name=snmpd state=restarted enabled=yes
  tags:
    - install

