#- name: add mhfmin group
#  action: group name=mhfmin gid=603 state=present
#  tags:
#     - account

- name: add mhfmin group
  action: group name={{item.name}} gid={{item.gid}} state=present
  with_items:
    - { name: 'mhfmin'  , gid: 613}
    - { name: 'postgres', gid: 26}
    - { name: 'capadmin', gid: 1001}


#- name: add mhfmin user
#  action: user name=mhfmin uid=603 group=mhfmin groups=wheel append=yes state=present force=yes
#  ignore_errors: yes
#  tags:
#     - account


- user: name={{item.name}} uid={{item.uid}} comment="{{item.comment}}" group={{item.group}} groups={{item.groups}}
  with_items:
    - { name: 'mhfmin'  , uid: 613 , group: 'mhfmin'  , groups: 'wheel' , comment: '' }
    - { name: 'postgres', uid: 26  , group: 'postgres', groups: ''      , comment: '' }
    - { name: 'capadmin', uid: 1001, group: 'capadmin', groups: 'wheel' , comment: 'administrator' }

