- hosts: '{{ hosts }}'
  user: root
  vars:
    username: '{{ username }}'
    saltstr: saltstr
  vars_prompt:
    - name: "new_password"
      prompt: "Enter new password"
      confirm: true
      private: yes
  tasks:
    - name: "create password salt"
      shell: echo somesalt | /usr/bin/md5sum | awk '{print $1}'
      register: password_salt

    - name: "create new password hash"
      command: python -c 'import crypt; print crypt.crypt("{{ new_password }}", "$1${{ password_salt.stdout }}$")'
      register: password_hash

    - name: "change password"
      user: name={{ username }} password={{ password_hash.stdout }} state=present

