- name: install required packages from repository
  action: yum name={{ item }} state=latest
  with_items:
    - java
  tags:
    - edgescape

- name: Creates directory
  file: path=/usr/local/src/edgescape state=directory
  tags:
    - edgescape

- name: copy src files
  action: copy src={{ item }} dest=/usr/local/src/edgescape/
  with_items:
    - edgescape.tgz
  tags:
    - edgescape

- name: extract source file
  action: shell tar xvzf {{ item }} chdir=/usr/local/src/edgescape
  with_items:
    - edgescape.tgz
  tags:
    - edgescape

- name: copy source file
  command: cp -pr /usr/local/src/edgescape /usr/local/
  tags:
    - edgescape

- name: copy edgescape configure file
  action: copy src={{ item }} dest=/usr/local/edgescape/
  with_items:
    - edgescape/config
    - edgescape/sbin
  tags:
    - edgescape

- name: copy edgescape init script
  action: template src=etc_init.d_edgescape dest=/etc/init.d/edgescape mode=0755
  tags:
    - edgescape

- name: add edgescape service
  action: shell chkconfig --add edgescape
  tags:
    - edgescape

- name: start edgescape service
  action: service name=edgescape state=started enabled=yes
  tags:
    - edgescape

- name: copy src files
  action: copy src={{ item }} dest=/usr/local/src/
  with_items:
    - mod_capedgescape.tar.gz
  tags:
    - mod_capedgescape

- name: module add
  action: copy src={{ item }} dest=/usr/local/src/
  with_items:
    - mod_capedgescape.tar.gz
  tags:
    - mod_capedgescape

- name: extract source file
  action: shell tar xvzf {{ item }} chdir=/usr/local/src
  with_items:
    - mod_capedgescape.tar.gz
  tags:
    - mod_capedgescape

- name: install module
  action: shell /usr/local/apache2/bin/apxs -c -I /usr/local/edgescape/api  {{ item }} chdir=/usr/local/src/mod_capedgescape/
  with_items:
    - mod_capedgescape.c 
  tags:
    - mod_capedgescape

- name: install module2
  action: shell /usr/local/apache2/bin/apxs -i -a {{ item }} chdir=/usr/local/src/mod_capedgescape/
  with_items:
    - mod_capedgescape.la
  tags:
    - mod_capedgescape


