- name: delete default nginx conf
  action: file path={{ item }} state=absent
  with_items:
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/conf.d/example_ssl.conf
  tags:
    - nata2

- name: put nata2.conf
  action: template src=nata2.conf dest=/etc/nginx/conf.d/
  tags:
    - nata2

- name: service nata2 start
  action: service name=nata2 state=restarted enabled=yes
  tags:
    - nata2

- name: service nginx start
  action: service name=nginx state=restarted enabled=yes
  tags:
    - nata2
