- name: create directory
  file: dest={{ item }} state=directory mode=0777 owner=zabbix group=zabbix
  with_items:
    - /opt/capcom/
    - /opt/capcom/zabbix/
    - /opt/capcom/zabbix/dat/
  tags:
    - memcached
    - zabbix

- name: copy memcached-tool
  action: copy src=memcached-tool dest=/usr/local/bin/ mode=0755
  tags:
    - memcached

- name: copy userparameter file
  copy: src=userparameter_memcached.conf dest=/etc/zabbix/zabbix_agentd.d/userparameter_memcached.conf
  register: userparameter
  tags:
    - memcached
    - zabbix

- name: restart zabbix-agent
  service: name=zabbix-agent state=restarted
  when: userparameter.changed
  tags:
    - zabbix
