- name: install required packages
  action: yum name={{ item }} state=latest enablerepo=epel,remi,rpmforge
  with_items:
    - openssl-devel
  tags:
    - ruby

- name: git clone rbenv
  action: git repo=https://github.com/sstephenson/rbenv.git dest=/usr/local/rbenv/ update=yes
  tags:
    - ruby

- name: git clone ruby-build
  action: git repo=https://github.com/sstephenson/ruby-build.git dest=/usr/local/rbenv/plugins/ruby-build/
  tags:
    - ruby

- name: add rbenv/bin to PATH
  action: lineinfile line="{{ item.line }}" dest=/root/.bash_profile
  with_items:
    - { line: 'export RBENV_ROOT=\"/usr/local/rbenv\"' }
    - { line: 'export PATH=\"${RBENV_ROOT}/bin:$PATH\"' }
    - { line: 'eval \"$(rbenv init -)\"' }
  tags:
    - ruby

- name: install ruby-build
  action: shell /usr/local/rbenv/plugins/ruby-build/install.sh
  tags:
    - ruby

- name: install ruby with ruby-build
  action: shell http_proxy={{ http_proxy }} /usr/local/rbenv/bin/rbenv install {{ ruby_version }}
  tags:
    - ruby

- name: rbenv rehash
  action: shell /usr/local/rbenv/bin/rbenv rehash
  tags:
    - ruby

- name: rbenv global
  action: shell /usr/local/rbenv/bin/rbenv global {{ ruby_version }}
  tags:
    - ruby

- name: export ruby PATH
  action: lineinfile regexp={{ item.regexp }} line="{{ item.line }}" dest=/root/.bash_profile
  with_items:
    - { line: 'export PATH=\"$PATH:/root/.rbenv/shims/\"' }
  tags:
    - ruby
