- hosts: '{{ hosts }}'
  sudo: yes
  vars_files:
     # common vars file
     - ../../common-vars/common.yml
     # platform vars file
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-{{ env }}.yml

  roles:
     - ../../system-roles/ddo/php/01_php_with-src
