- hosts: '{{ hosts }}'
  sudo: no
  vars_files:
     # common vars file
     - ../../common-vars/common.yml
     # platform vars file
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-{{ env }}.yml
     # database vars file 
     #- ../../system-vars/{{ system }}-{{ db }}-{{ env }}.yml

  roles:
     - ../../system-roles/i3/percona/01_install_percona-server
     - ../../system-roles/i3/percona/02_setup_percona-server
