- name: clear record 127.0.0.1
  action: lineinfile dest=/etc/hosts regexp='^127.0.0.1' line='127.0.0.1          localhost localhost.domain'
  tags:
    - hosts

- name: delete ipv6 record
  action: lineinfile dest=/etc/hosts regexp='::' state=absent
  tags:
    - hosts
