- name: install required packages from repository
  action: yum name={{ item }} state=latest
  with_items:
    - libxml2-devel
    - openssl-devel
    - curl-devel
  tags:
    - php
 
- name: download php source file
  action: shell http_proxy={{ http_proxy }} wget -nc http://jp1.php.net/distributions/php-{{ php_version }}.tar.gz  chdir=/usr/local/src/
  tags:
    - php

- name: extract source file
  action: shell tar xvzf {{ item }} chdir=/usr/local/src/
  with_items:
    - php-{{ php_version }}.tar.gz
  tags:
    - php

- name: copy php configure file
  action: template src=php-configure.sh dest=/usr/local/src/php-{{ php_version }}/
  tags:
    - php

- name: exec php configure file
  action: shell sh php-configure.sh chdir=/usr/local/src/php-{{ php_version }}/
  tags:
    - php

- name: make install php
  action: shell make && make install chdir=/usr/local/src/php-{{ php_version }}/
  tags:
    - php

- name: create symlink for php home directory
  action: file state=link src=/usr/local/php-{{ php_version }} dest=/usr/local/php
  tags:
     - php

- name: create php error-log directories
  action: file state=directory path={{ item }}  owner=nginx
  with_items:
    - /var/log/php/php-error
  tags:
    - php
