- name: configure /etc/pam.d/su
  lineinfile: dest=/etc/pam.d/su owner=root group=root mode=0644 backup=yes {{item}}
  with_items:
    - regexp='^auth.*required.*pam_wheel.so use_uid' line='auth           required        pam_wheel.so use_uid' insertafter='^#auth.*required.*pam_wheel.so use_uid'
  tags: wheel

- name: configure /etc/login.defs
  lineinfile: dest=/etc/login.defs owner=root group=root mode=0644 backup=yes {{item}}
  with_items:
    - regexp='^SU_WHEEL_ONLY' line='SU_WHEEL_ONLY yes' insertafter='^ENCRYPT_METHOD'
  tags: wheel

