- name: install required packages
  action: yum name={{ item }} state=latest
  with_items:
    - postfix
    - procmail
  tags:
    - mail
    - cog

- name: update main.cf
  action: template src=main.cf dest=/etc/postfix/main.cf
  tags:
    - cog
    - mail

- name: restart postfix
  action: service name=postfix state=restarted
  tags:
    - cog
    - mail

- name: change permission of maillog
  action: file dest=/var/log/maillog mode=0644
  tags:
    - cog
    - mail

- name: copy swaks
  action: copy src=swaks dest=/usr/local/bin/ mode=0755
  tags:
    - cog
    - mail
