- name: install required package
  yum: name=libselinux-python state=latest
  tags:
    - install

- name: setup zabbix repository
  copy: src=zabbix.repo dest=/etc/yum.repos.d/
  tags:
    - install

- name: install zabbix agent via yum repository
  yum: name={{item}} state=latest enablerepo=zabbix24 disable_gpg_check=yes
  with_items:
    - zabbix
    - zabbix-agent
    - zabbix-sender
  tags:
    - install

- name: update zabbix agent conf
  template: src=zabbix_agentd.conf dest=/etc/zabbix/ backup=yes
  tags:
    - setup

- name: copy common userparameter
  copy: src=userparameter_common.conf dest=/etc/zabbix/zabbix_agentd.d/
  tags:
    - setup

- name: start zabbix agent service
  service: name=zabbix-agent state=restarted enabled=yes
  tags:
    - setup
