- name: nopass check
  action: shell mysql -uroot -e 'show global status;'
  register: nopass
  tags:
    - zabbix
    - mysql

- name: create directory
  action: file dest={{ item }} state=directory mode=0777 owner=zabbix group=zabbix
  with_items:
    - /opt/capcom/
    - /opt/capcom/zabbix/
    - /opt/capcom/zabbix/dat/
  tags:
    - zabbix
    - mysql

- name: create directory
  action: file dest={{ item }} state=directory mode=0700 owner=zabbix group=zabbix
  with_items:
    - /var/lib/zabbix/
  tags:
    - zabbix
    - mysql

- name: create monitor user
  action: mysql_user name=monitor password=monitor priv="*.*:SELECT,USAGE,REPLICATION CLIENT" state=present
  tags:
    - zabbix
    - mysql

- name: copy .my.cnf to /var/lib/zabbix/.my.cnf
  action: copy src=.my.cnf dest=/var/lib/zabbix/ owner=zabbix group=zabbix mode=0600
  tags:
    - setup

- name: copy userparameter file
  action: copy src=userparameter_mysql.conf dest=/etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf
  register: userparameter
  tags:
    - setup

- name: restart zabbix-agent
  action: service name=zabbix-agent state=restarted
  when: userparameter.changed
  tags:
    - setup
