- name: install required packages from repository
  action: yum name={{ item }} state=latest
  with_items:
    - openssl
    - openssl-devel
    - pcre-devel
    - zlib-devel
  tags:
    - apache

- name: download apr source file
  action: shell http_proxy={{ http_proxy }} wget -nc http://www.us.apache.org/dist/apr/apr-{{ apr_version }}.tar.gz  chdir=/usr/local/src/
  tags:
    - apache

- name: extract source file
  action: shell tar xvzf {{ item }} chdir=/usr/local/src/
  with_items:
    - apr-{{ apr_version }}.tar.gz
  tags:
    - apache

- name: download apr-util source file
  action: shell http_proxy={{ http_proxy }} wget -nc http://www.us.apache.org/dist/apr/apr-util-{{ apr_util_version }}.tar.gz  chdir=/usr/local/src/
  tags:
    - apache

- name: extract source file
  action: shell tar xvzf {{ item }} chdir=/usr/local/src/
  with_items:
    - apr-util-{{ apr_util_version }}.tar.gz
  tags:
    - apache

- name: download apache source file
  action: shell http_proxy={{ http_proxy }} wget -nc http://archive.apache.org/dist/httpd/httpd-{{ apache_version }}.tar.gz  chdir=/usr/local/src/
  tags:
    - apache

- name: extract source file
  action: shell tar xvzf {{ item }} chdir=/usr/local/src/
  with_items:
    - httpd-{{ apache_version }}.tar.gz
  tags:
    - apache

- name: copy apr source file
  command: mv /usr/local/src/apr-{{ apr_version }} /usr/local/src/httpd-{{ apache_version }}/srclib/apr
  tags:
    - apache

- name: copy apr-utils source file
  command: mv /usr/local/src/apr-util-{{ apr_util_version }} /usr/local/src/httpd-{{ apache_version }}/srclib/apr-util
  tags:
    - apache

- name: copy apache configure file
  action: template src=apache-configure.sh dest=/usr/local/src/httpd-{{ apache_version }}/
  tags:
    - apache

- name: exec apache configure file
  action: shell sh apache-configure.sh chdir=/usr/local/src/httpd-{{ apache_version }}/
  tags:
    - apache

- name: make install apache
  action: shell make && porg -lD "make install" chdir=/usr/local/src/httpd-{{ apache_version }}/
  tags:
    - apache

- name: create symlink for apache home directory
  action: file state=link src=/usr/local/apache{{apache_version}} dest=/usr/local/apache2
  tags:
     - apache

- name: create apache log directories
  action: file state=directory path={{ item }}
  with_items:
    - /var/log/httpd/
  tags:
    - apache

- name: create symlink for apache log directory (1/2)
  action: file state=absent path=/usr/local/apache2/logs/
  tags:
    - apache

- name: create symlink for apache log directory (2/2)
  action: file state=link src=/var/log/httpd dest=/usr/local/apache2/logs
  tags:
    - apache

- name: create apache group
  action: group name=apache gid=48
  tags:
    - apache

- name: create apache user
  action: user name=apache uid=48 group=apache createhome=yes home=/var/www/ shell=/sbin/nologin
  tags:
    - apache

- name: copy apache init script
  action: template src=etc_init.d_httpd dest=/etc/init.d/httpd mode=0755
  tags:
    - apache

- name: add httpd service
  action: shell chkconfig --add httpd
  tags:
    - apache

- name: start httpd service
  action: service name=httpd state=started enabled=yes
  tags:
    - apache

- name: httpd configfile repair
  command: sed -i'.org' -e 's/#LoadModule slotmem_shm_module modules\/mod_slotmem_shm.so/LoadModule slotmem_shm_module modules\/mod_slotmem_shm.so/g' /usr/local/apache2/conf/httpd.conf
  tags:
    - apache

