- name: update /etc/yum.conf
  action: lineinfile dest=/etc/yum.conf {{item}}
  with_items:
    - regexp='^keepcache' line='keepcache=1'
    - regexp='exclude=kernel' line='exclude=kernel* centos-release*'
  tags:
    - yum

- name: setup remi repository
  action: copy src=remi-enterprise.repo dest=/etc/yum.repos.d/
  tags:
    - yum

- name: setup epel repository
  action: copy src=epel.repo dest=/etc/yum.repos.d/
  tags:
    - yum

- name: delete epel-testing repository
  action: file path=/etc/yum.repos.d/epel-testing.repo state=absent
  tags:
    - yum

- name: setup rpmforge repository
  action: copy src=rpmforge.repo dest=/etc/yum.repos.d/
  tags:
    - yum

- name: update all package
  action: yum name=* state=latest disable_gpg_check=yes
  tags:
    - yum
