- name: update /etc/yum.conf
  action: lineinfile dest=/etc/yum.conf {{item}}
  with_items:
    - regexp='^keepcache' line='keepcache=1'
    - regexp='.*exclude=kernel' line='exclude=kernel* centos-release*'
    - regexp='.*proxy=.*' line='proxy={{ http_proxy }}'
  tags:
    - yum

- name: install base packages in [Base] 1/4
  action: yum pkg={{ item }} state=latest
  with_items:
    - abrt-addon-ccpp
    - abrt-addon-kerneloops
    - abrt-addon-python
    - abrt-cli
    - blktrace
    - bzip2
  tags:
    - packages

- name: install base packages in [Base] 2/4
  action: yum pkg={{ item }} state=latest
  with_items:
    - eject
    - ethtool
    - libselinux-python
    - man
    - man-pages
    - microcode_ctl
    - mlocate
  tags:
    - packages

- name: install base packages in [Base] 3/4
  action: yum pkg={{ item }} state=latest
  with_items:
    - ntp
    - ntpdate
    - openssh
    - prelink
    - rsync
    - strace
    - sysstat
  tags:
    - packages

- name: install base packages in [Base] 4/4
  action: yum pkg={{ item }} state=latest
  with_items:
    - tcpdump
    - time
    - unzip
    - wget
    - which
    - yum-plugin-security
    - yum-utils
    - zip
  tags:
    - packages

- name: install base packages in [Performance Tools]
  action: yum pkg={{ item }} state=latest
  with_items:
    - dstat
  tags:
    - packages

- name: install base packages in [Networking Tools]
  action: yum pkg={{ item }} state=latest
  with_items:
    - nc
    - nmap
  tags:
    - packages

- name: install base packages in [Legacy UNIX compatibility]
  action: yum pkg={{ item }} state=latest
  with_items:
    - telnet
    - xinetd
  tags:
    - packages

- name: install base packages in [Development Tools]
  action: yum pkg={{ item }} state=latest
  with_items:
    - gcc
    - make
  tags:
    - packages

- name: install base packages in [System Management]
  action: yum pkg={{ item }} state=latest
  with_items:
    - net-snmp-utils
  tags:
    - packages

- name: install extra packages
  action: yum pkg={{ item }} state=latest
  with_items:
    - dmidecode
  tags:
    - extra-packages

