#!/bin/sh

###############
## apache log ##
################
DT=`date '+%Y%m%d' --date '1 days ago'`
N_YM=`date '+%Y%m'`

dirs="/var/log/httpd"

################

for filepath in ${dirs}/*
do
	echo ${filepath}
	if [ ! -d ${filepath}/${N_YM} ]; then
		mkdir -p ${filepath}/${N_YM}
	fi

	gzip ${filepath}/*_log.$DT
	mv ${filepath}/*_log.$DT.gz ${filepath}/${N_YM}

	find ${dirs} -mtime +30 -name '*.gz' | xargs rm -f
done


exit 0
