- name: copy source file
  copy : src=openssl-0.9.8g.tar.gz dest=/usr/local/src

- name : tar
  command : tar xvfz openssl-0.9.8g.tar.gz chdir=/usr/local/src creates=/usr/local/src/openssl-0.9.8g

- name : config for OS ver5
  command : ./config --shared chdir=/usr/local/src/openssl-0.9.8g
  when: "ansible_distribution_major_version == '5'"

- name : config for OS ver6
  command : ./config --shared no-asm chdir=/usr/local/src/openssl-0.9.8g 
  when: "ansible_distribution_major_version == '6'"

- name : make
  command : make chdir=/usr/local/src/openssl-0.9.8g

- name : make install
  command : make install chdir=/usr/local/src/openssl-0.9.8g

