- hosts: '{{ hosts }}'
  sudo: no
  vars_files:
     # common vars file
     - ../../common-vars/common.yml
     # platform vars file
     - ../../platform-vars/{{ platform }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-{{ env }}.yml
     # system vars file
     - ../../system-vars/{{ system }}-gamedb-9.ymf

  roles:
    - ../../system-roles/xbmhf/26_2_postgres_pgrman_shell

