- name: install php-pecl-apc
  yum: name=php-pecl-apc state=latest enablerepo=remi,remi-php55
  tags:
    - php

- name: install php-ldap
  yum: name=php-ldap state=latest enablerepo=remi,remi-php55
  tags:
    - php

- name: update php.ini
  copy: src=php.ini dest=/etc/
  tags:
    - php

- name: delete default nginx conf
  action: file path={{ item }} state=absent
  with_items:
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/conf.d/example_ssl.conf
  tags:
    - nginx

- name: add zabbix.conf to /etc/nginx/conf.d
  copy: src=zabbix.conf dest=/etc/nginx/conf.d/
  tags:
    - nginx

- name: copy zabbix.conf.php to /etc/zabbix/web/
  action: copy src=zabbix.conf.php dest=/etc/zabbix/web/
  tags:
    - zabbix
    - nginx

- name: restart nginx & php-fpm
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - nginx
    - php-fpm
  tags:
    - nginx

- name: mkdir custom php directory
  file: state=directory path=/usr/share/zabbix/custom/ mode=0755
  tags:
    - zabbix

- name: copy custom php
  copy: src=printtext.php dest=/usr/share/zabbix/custom/
  tags:
    - zabbix


- name: change php file owner to nginx
  action: file path={{ item }} owner=nginx group=nginx recurse=yes
  with_items:
    - /etc/zabbix/web/
    - /usr/share/zabbix/
  tags:
    - zabbix

