- name: update zabbix_server.conf
  copy: src=zabbix_server.conf dest=/etc/zabbix/
  tags:
    - zabbix

- name: start zabbix-server
  service: name=zabbix-server state=restarted enabled=yes
  tags:
    - zabbix

- name: create zabbix script directory
  action: file path={{ item }} state=directory owner=zabbix group=zabbix mode=0755
  with_items:
    - /opt/capcom/
    - /opt/capcom/zabbix/
    - /opt/capcom/zabbix/bin/
    - /opt/capcom/zabbix/sql/
    - /opt/capcom/zabbix/lst/
    - /opt/capcom/zabbix/dat/
  tags:
    - zabbix

- name: update zabbix script
  action: copy src={{ item }} dest=/opt/capcom/zabbix/bin/ mode=0755 owner=zabbix group=zabbix
  with_items:
    - zabbix_getvaluemap.sh
    - zabbix_addvaluemap.sh
  tags:
    - zabbix

- name: copy zabbix list file
  action: copy src={{ item }} dest=/opt/capcom/zabbix/lst/
  with_items:
    - zabbix_valuemap.lst
  tags:
    - zabbix

- name: copy zabbix sql file
  action: copy src={{ item }} dest=/opt/capcom/zabbix/sql/
  with_items:
    - zabbix_regexps.sql
    - zabbix_expressions.sql
    - zabbix_config.sql
  tags:
    - zabbix

- name: import valuemap
  action: shell /opt/capcom/zabbix/bin/zabbix_addvaluemap.sh /opt/capcom/zabbix/lst/zabbix_valuemap.lst
  tags:
    - zabbix

- name: exec sql expressions
  action: shell mysql -uzabbix -pzabbix zabbix < {{ item }}
  with_items:
    - /opt/capcom/zabbix/sql/zabbix_regexps.sql
    - /opt/capcom/zabbix/sql/zabbix_expressions.sql
    - /opt/capcom/zabbix/sql/zabbix_config.sql
  tags:
    - zabbix
